package dam_A51706.coolweatherapptp3.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA3CFF8)
val md_theme_light_onPrimary = Color(0xFF295680)
val md_theme_light_primaryContainer = Color(0xFFDAE5EF)
val md_theme_light_onPrimaryContainer = Color(0xFFF4F4F4)
val md_theme_light_secondary = Color(0xFF295680)
val md_theme_light_onSecondary = Color(0xFFF4F4F4)
val md_theme_light_secondaryContainer = Color(0xFF849EB6)
val md_theme_light_onSecondaryContainer = Color(0xFF295680)
val md_theme_light_tertiary = Color(0xFFFFA550)
val md_theme_light_onTertiary = Color(0xFFF4F4F4)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBB8)
val md_theme_light_onTertiaryContainer = Color(0xFFFFA550)
val md_theme_light_surface = Color(0xFFF4F4F4)

val md_theme_dark_primary = Color(0xFFA3CFF8)
val md_theme_dark_onPrimary = Color(0xFFF4F4F4)
val md_theme_dark_primaryContainer = Color(0xFFDAE5EF)
val md_theme_dark_onPrimaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_secondary = Color(0xFFFFA550)
val md_theme_dark_onSecondary = Color(0xFFF4F4F4)
val md_theme_dark_secondaryContainer = Color(0xFFFFDBB8)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFA550)
val md_theme_dark_tertiary = Color(0xFFF4F4F4)
val md_theme_dark_onTertiary = Color(0xFF333333)
val md_theme_dark_tertiaryContainer = Color(0xFFCFCECE)
val md_theme_dark_onTertiaryContainer = Color(0xFFF4F4F4)
val md_theme_dark_surface = Color(0xFF295680)